// Generated by CoffeeScript 1.6.3
(function() {
  jQuery(function() {
    return $.langsceneUi = {
      setup: function() {
        var onWindowResize,
          _this = this;
        console.log('init langscene ui');
        this._createUi();
        onWindowResize = function() {
          return _this.$uiLangScene.css({
            top: $(window).height() - _this.$uiLangScene.height(),
            left: $(window).width() - _this.$uiLangSceneBtns.width() - 10
          });
        };
        $(window).resize(onWindowResize);
        onWindowResize();
        this.$uiLangSceneBtns.find(".langscene-btn-pickword").click(function() {
          if ($.wordpicker.picking) {
            $(this).removeClass('langscene-btn-pickword-picking').text('取消');
            $.wordpicker.disable();
          } else {
            $(this).addClass('langscene-btn-pickword-picking').text('取词');
            $.wordpicker.enable();
          }
          return false;
        });
        $.wordpicker.on('picked', function(word, $event) {
          if (!word) {
            return;
          }
          _this.pickedWord = word;
          $.wordpicker.disable();
          _this.$uiPickupWordBtn.text(word);
          _this.$uiPickupWord.show().css({
            top: $event.pageY - _this.$uiPickupWord.outerHeight() - 10,
            left: $event.pageX - _this.$uiPickupWord.outerWidth() / 2
          });
          return _this.pickedUp = true;
        });
        return $(document).click(function(event) {
          _this.$uiPickupWord.hide();
          if (!_this.pickedUp) {
            return;
          }
          _this.pickedUp = false;
          if (event.originalEvent.srcElement === _this.$uiPickupWordBtn[0]) {
            console.log('bingo!', _this.pickedWord);
          }
          return event.originalEvent.returnValue = false;
        });
      },
      _createUi: function() {
        this.$uiLangScene = $("<div id='langscene-ui'>\n    <div class='langscene-btns'>\n        <div class='langscene-btn-pickword'></div>\n    </div>\n</div>").appendTo(document.body).css({
          position: 'fixed',
          'z-index': 10000
        });
        this.$uiLangSceneBtns = this.$uiLangScene.find('.langscene-btns');
        this.$uiPickupWord = $("<div class='langscene-pickup-word'>\n<div class='langscene-pickup-btn'></div>\n</div>").appendTo(document.body);
        return this.$uiPickupWordBtn = this.$uiPickupWord.find('.langscene-pickup-btn');
      },
      pickedUp: false,
      pickedWord: void 0
    };
  });

}).call(this);
